- Energy Service|{Residential & Commercial}|Floor Space:
    description: Energy service demand for conditioned floor space
      in {Residential & Commercial} buildings
    unit: billion m2
    tier: 2